backend:
  name: github
  repo: emoeem/emoeem.github.io
  branch: main
  base_url: https://decap-oauth-kappa.vercel.app

media_folder: source/medias
public_folder: /medias

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "封面图", name: "img", widget: "image", required: false }
      - { label: "摘要", name: "summary", widget: "text", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
